/* eslint-disable */
export default {
  "key": "faq",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "sectionTitle": "Frequently Asked Questions",
        "sectionSubtitle": "Everything you need to know about the His Word application features, performance, and data policies.",
        "catAppTitle": "App & Features",
        "catAppDesc": "General questions about features, translations, and reading tools.",
        "q1Title": "What translations are supported in His Word?",
        "q1Content": "His Word includes the American Standard Version (ASV) and the World English Bible (WEB). Both translations are stored fully offline on your device, allowing you to switch between them instantly with zero network delay.",
        "q2Title": "Is His Word free to use, and are there ads?",
        "q2Content": "Yes, His Word is 100% free, open-source, and does not contain any advertisements, subscription models, or hidden in-app purchases.",
        "q3Title": "How do the daily devotionals and notifications work?",
        "q3Content": "The app features a custom notification queue that schedules devotionals locally on your device. It includes holiday-specific scripture selections (such as Christmas, Easter, and Good Friday) and automatically manages its local queue so you never miss a Verse of the Day.",
        "q4Title": "Does the app track what I read?",
        "q4Content": "No. His Word features a local Reading History tracker that logs your last 10 reading sessions with deduplication and relative timestamps. This record remains strictly on your device and is never transmitted to any analytics or tracking services.",
        "q5Title": "Can I filter scriptures by testament or category?",
        "q5Content": "Yes. The search and navigation views include dynamic category tags (such as Law, History, Poetry, Gospels, and Epistles), allowing you to quickly filter search results and navigate to specific genres of biblical literature.",
        "catPrivacyTitle": "Privacy & Offline Access",
        "catPrivacyDesc": "How your data and connection status are managed.",
        "q6Title": "Where is my journaling and reading data stored?",
        "q6Content": "All data—including your reflection notes, bookmarks, reading logs, and color-coded verse highlights—is stored locally on your device using AsyncStorage. None of your data is ever uploaded to external databases or cloud servers.",
        "q7Title": "Do I need an active internet connection to read?",
        "q7Content": "No. His Word is designed as a true offline-first application. Once installed, all scriptures, Text-to-Speech audio reading, search tools, and devotionals are fully accessible without Wi-Fi or cellular data.",
        "q8Title": "What personal details are required to use the app?",
        "q8Content": "None. There are no sign-up forms, email verifications, user accounts, or social logins. Your identity remains 100% anonymous.",
        "catPerfTitle": "Performance & Hardware Sensors",
        "catPerfDesc": "Details on advanced mobile capabilities, caching, and background threads.",
        "q9Title": "How does the 'Shake-to-Capture' sharing feature work?",
        "q9Content": "When you shake your phone while reading, the device's accelerometer detects the motion and triggers our on-device canvas renderer. It provides tactile haptic feedback, dynamically composes a high-resolution scripture card with your active theme, and opens the native OS share sheet.",
        "q10Title": "Why does the app request notification and sensor access?",
        "q10Content": "Notifications are requested solely to deliver your opt-in daily devotionals. Sensor (accelerometer) access is requested strictly to detect the shake gesture for sharing cards while reading. None of this sensor or notification data ever leaves your device.",
        "q11Title": "What is the LRU Bible module cache?",
        "q11Content": "To keep the memory footprint minimal on older devices, the app utilizes a custom Least Recently Used (LRU) cache. It dynamically loads book translations when needed and caches active chapters in memory, preventing memory bloat and app crashes.",
        "q12Title": "How does the non-blocking search work?",
        "q12Content": "Searching a massive text database on mobile can cause stutter. His Word pairs a 200ms debounce with asynchronous timer micro-task chunking to run queries on separate execution cycles, ensuring the search bar remains silky smooth while querying all 66 books.",
        "q13Title": "How does the high-fidelity image exporter work?",
        "q13Content": "When you trigger a share, the app uses a hidden WebView to render the scripture, highlight colors, and reflection text onto a virtual HTML5 Canvas using premium typography. The canvas outputs a high-resolution PNG locally for sharing.",
        "q14Title": "How can I submit bugs, request features, or contact the developer?",
        "q14Content": "For support, bug submissions, or feature requests, you can email the developer directly at ",
        "q14LinkText": " Alternatively, if you want to engage directly and publicly with the developer, you can leave a comment on this ",
        "q14BlogText": "blog post"
      },
      "zu": {
        "sectionTitle": "Imibuzo Ejwayelekile Ukubuzwa",
        "sectionSubtitle": "Konke odinga ukukwazi mayelana nezici ze-His Word, ukusebenza kwayo, kanye nenqubomgomo yobumfihlo.",
        "catAppTitle": "Uhlelo Lokusebenza & Nezici Zalo",
        "catAppDesc": "Imibuzo ejwayelekile mayelana nezici, izinguqulo, namathuluzi okufunda.",
        "q1Title": "Yiziphi izinguqulo ezisekelwa ku-His Word?",
        "q1Content": "I-His Word ihlanganisa i-American Standard Version (ASV) ne-World English Bible (WEB). Zombili lezi zinguqulo zigcinwa ngokuphelele kudivayisi yakho ngaphandle kwe-inthanethi, okukuvumela ukuthi ushintshe phakathi kwazo ngokushesha.",
        "q2Title": "Ingabe i-His Word imahhala ukuyisebenzisa, futhi ingabe kukhona izikhangiso?",
        "q2Content": "Yebo, i-His Word imahhala ngo-100%, ivulekile (open-source), futhi ayinazo nhlobo izikhangiso, izindlela zokubhalisa, noma ukukhokha okufihliwe ngaphakathi kohlelo.",
        "q3Title": "Isebenza kanjani imikhuleko yansuku zonke nezaziso?",
        "q3Content": "Uhlelo lusebenzisa uhlu lwezaziso oluhlela amavesi osuku endaweni kudivayisi yakho. Kuhlanganisa nemibhalo ekhethekile yezinsuku zamaholide (njengoKhisimusi, Iphasika, noLwesihlanu Olungcwele) futhi luphatha uhlu lwalo ukuqinisekisa ukuthi awuphuthelwa yiVesi Losuku.",
        "q4Title": "Ingabe uhlelo luyakulandelela lokho engikufundayo?",
        "q4Content": "Cha. I-His Word inesilandeleli somlando wokufunda sasendaweni esigcina izikhathi zakho zokugcina eziyishumi zokufunda. Lolu hlu luhlala kuphela kudivayisi yakho futhi alwabelwa muntu noma izinsiza ze-analytics.",
        "q5Title": "Ngingakwazi ukuhlunga imibhalo ngeTestamente noma ngesigaba?",
        "q5Content": "Yebo. Imibono yokusesha neyokuzulazula ihlanganisa amathegi ezigaba (njengoMthetho, Umlando, Izinkondlo, amaVangeli, nezincwadi zabaPhostoli), okukuvumela ukuthi uhlunge ngokushesha imiphumela yosesho.",
        "catPrivacyTitle": "Ubumfihlo Nokusebenza Ngaphandle Kwe-inthanethi",
        "catPrivacyDesc": "Ukuthi idatha yakho nobumfihlo kulawulwa kanjani.",
        "q6Title": "Igciniwe kuphi idatha yami yokubhala namanothi okufunda?",
        "q6Content": "Yonke idatha—kuhlanganise namanothi akho okuzindla, amabhukumaka, amarekhodi wokufunda, nokugqamisa amavesi ngemibala—igcinwa kudivayisi yakho kuphela kusetshenziswa i-AsyncStorage. Ayikho idatha yakho eyake yalayishwa kumaseva angaphandle noma efwini.",
        "q7Title": "Ingabe ngidinga uxhumano lwe-inthanethi olusebenzayo ukuze ngifunde?",
        "q7Content": "Cha. I-His Word yakhelwe njengohlelo olusebenza ngokuphelele ngaphandle kwe-inthanethi. Uma selufakiwe, yonke imibhalo, umsindo wokufundelwa, amathuluzi okusesha, nemikhuleko kutholakala ngaphandle kwe-Wi-Fi noma idatha yeselula.",
        "q8Title": "Imiphi imininingwane yomuntu siqu edingekayo ukuze usebenzise uhlelo?",
        "q8Content": "Ayikho nhlobo. Awukho amafomu okubhalisa, ukuqinisekiswa kwe-imeyili, ama-akhawunti abasebenzisi, noma ukungena ngemithombo yezokuxhumana. Ubuwena buhlala buyimfihlo ngokuphelele.",
        "catPerfTitle": "Ukusebenza Nezinzwa Zehardware",
        "catPerfDesc": "Imininingwane emayelana namakhono eselula athuthukile, ukugcina kwesikhashana, nokusebenza kwangemuva.",
        "q9Title": "Isebenza kanjani isici sokwabelana se-'Shake-to-Capture'?",
        "q9Content": "Uma unyakazisa ifoni yakho ngenkathi ufunda, inzwa yokunyakaza (accelerometer) ithola ukunyakaza bese iqala injini yokwenza amakhadi. Ikunikeza ukuthinta okudlidlizayo (haptic), yakhe ikhadi le-vesi elihle kakhulu elinetimu yakho, bese ivula iwindi lokwabelana ledivayisi.",
        "q10Title": "Kungani uhlelo lucela ukufinyelela kwesaziso nenzwa?",
        "q10Content": "Izaziso zicelwa kuphela ukuletha amavesi osuku owakhethile. Izimvume zenzwa zicelwa kuphela ukuthola ukunyakaza kokudala amakhadi okwabelana ngenkathi ufunda. Ayikho kule datha eqoqwayo noma edluliselwa ngaphandle kwedivayisi yakho.",
        "q11Title": "Yini inqolobane yemojula yeBhayibheli ye-LRU?",
        "q11Content": "Ukuze kugcinwe ukusetshenziswa kwememori kuncane kumadivayisi amadala, uhlelo lusebenzisa inqolobane ye-Least Recently Used (LRU). Ilayisha izinguqulo zezincwadi lapho zidingeka futhi igcine izahluko ezisebenzayo ememorini ukuvimbela ukuphahlazeka kohlelo.",
        "q12Title": "Isebenza kanjani injini yokusesha engaphazamisi ukusebenza kwe-UI?",
        "q12Content": "Ukusesha umbhalo omkhulu wesizindalwazi kuselula kungadala ukunensa. I-His Word ihlanganisa ukubambezela (debounce) nemisebenzi emincane ye-asynchronous ukuhlunga imibhalo ngokwezigaba, ukuqinisekisa ukuthi ibha yosesho ihlala ishesha futhi ibushelelezi ngenkathi ihlola zonke izincwadi ezingama-66.",
        "q13Title": "Isebenza kanjani injini yokukhiqiza amakhadi ezithombe ezisezingeni eliphezulu?",
        "q13Content": "Uma uqala ukwabelana, uhlelo lusebenzisa i-WebView efihliwe ukubhala umbhalo, imibala egqanyisiwe, namanothi akho ku-HTML5 Canvas kusetshenziswa ubuciko bokubhala obusezingeni eliphezulu. Le canvas ibe isikhiqiza isithombe se-PNG esiphezulu endaweni ukuze wabelane ngaso.",
        "q14Title": "Ngingazithumela kanjani iziphazamisi, ngicele izici, noma ngithinte unjiniyela?",
        "q14Content": "Ukuze uthole ukwesekwa, ukuthumela iziphazamisi, noma ukucela izici ezintsha, ungathumela i-imeyili kunjiniyela ngqo ku- ",
        "q14LinkText": " Kungenjalo, uma ufuna ukuxhumana ngqo nonjiniyela esidlangalaleni, ungashiya umbono wakho kuleli ",
        "q14BlogText": "bhalo lebhulogi"
      }
    }
  },
  "localIds": [
    "faq::local::src\\components\\Faq.content.ts"
  ]
} as const;
